version: "3.8"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./src:/app/src
      - ./assets:/app/assets
      - ./.env:/app/.env
    environment:
      - PYTHONPATH=/app
      - NLTK_DATA=/nltk_data
      - GROQ_API_KEY=${GROQ_API_KEY}
    command: uvicorn src.app:app --host 0.0.0.0 --port 8000 --reload
